packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: "19.2.5"
  react-dom: "19.2.5"
  react-hook-form: "^7.72.1"
  zod: "^4.3.6"
  "@types/react": "19"
  "@types/react-dom": "19"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 10800

minimumReleaseAgeExclude:
  - "@typescript/native-preview"
  - oxfmt
  - oxlint

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - lefthook
