ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 10800

minimumReleaseAgeExclude:
  - "@typescript/native-preview"
  - oxfmt
  - oxlint

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - lefthook
